"""Capture the HuggingFace reference fixture — the frozen answer key that every
later version of the engine is graded against.

For each canonical prompt we run HF's forward pass in a manual greedy loop (not
generate(), because we want the RAW logits, not generate()'s post-processed
scores) and record:

  - input_ids      : the tokenized prompt
  - greedy_ids     : the 50 greedily-decoded continuation tokens  (token-for-token key)
  - step0_logits   : full fp16 logit vector at the first decode step (strict numeric key)
  - topk_ids/vals  : top-5 (id, logit) at every step (cheap per-step ranking key)

Run:  python -m tests.capture_reference
"""
from __future__ import annotations

import torch
import transformers

from nano_infer import config
from nano_infer.hf_ref import encode_prompt, load_hf

TOPK = 5


@torch.no_grad()
def greedy_capture(model, input_ids, max_new_tokens: int):
    """Manual greedy decode capturing logits, with NO KV cache — the full sequence
    is recomputed every step, exactly matching nano-infer's Phase 1 greedy_decode.

    Why no cache: in fp16, the with-cache path (1 new query vs cached keys) and the
    no-cache path (full-sequence recompute) accumulate rounding slightly
    differently — enough to flip a near-tied token. The answer key must be
    generated by the SAME procedure the engine under test uses, or a benign
    near-tie reads as a false failure. Phase 1's engine is no-cache, so is this."""
    device = input_ids.device
    greedy_ids: list[int] = []
    step0_logits = None
    topk_ids = torch.empty(max_new_tokens, TOPK, dtype=torch.long)
    topk_vals = torch.empty(max_new_tokens, TOPK, dtype=torch.float16)

    seq = input_ids
    for step in range(max_new_tokens):
        out = model(seq, use_cache=False)      # full recompute, no cache
        logits = out.logits[:, -1, :].float()  # [1, vocab], upcast for stable topk

        if step == 0:
            step0_logits = logits.squeeze(0).to(torch.float16).cpu().clone()

        vals, ids = torch.topk(logits.squeeze(0), TOPK)
        topk_ids[step] = ids.cpu()
        topk_vals[step] = vals.to(torch.float16).cpu()

        # Greedy selection uses torch.argmax, NOT topk's first index. On an exact
        # logit tie they can disagree: argmax is documented to return the FIRST
        # maximal index, topk makes no such promise. The engine decodes with
        # argmax, so the answer key must too -- otherwise a tie is recorded as a
        # divergence with bit-identical logits. Rare in fp16; common in bf16,
        # whose 7-bit mantissa makes exact ties frequent (ROADMAP #42: at
        # Qwen2.5-1.5B prompt 2 step 20 the top two logits are both exactly 18.25,
        # argmax picks 2980 and topk 9645).
        next_id = int(logits.squeeze(0).argmax().item())
        greedy_ids.append(next_id)

        seq = torch.cat([seq, torch.tensor([[next_id]], device=device)], dim=1)

    return {
        "input_ids": input_ids.squeeze(0).cpu(),
        "greedy_ids": torch.tensor(greedy_ids, dtype=torch.long),
        "step0_logits": step0_logits,
        "topk_ids": topk_ids,
        "topk_vals": topk_vals,
    }


def main():
    torch.manual_seed(config.SEED)
    config.FIXTURES_DIR.mkdir(parents=True, exist_ok=True)

    # Capture against EAGER attention — HF's canonical reference math, not its
    # fused SDPA kernel. SDPA differs from eager by ~0.1 logit over 24 layers,
    # enough to flip a near-tied token; a correctness baseline must use the
    # deterministic reference impl, which is exactly what our engine mirrors.
    print(f"Loading {config.MODEL_NAME} in {config.DTYPE} on {config.DEVICE} (eager) ...")
    model, tok = load_hf(attn_implementation="eager")

    per_prompt = []
    for i, prompt in enumerate(config.PROMPTS):
        ids = encode_prompt(tok, prompt)
        cap = greedy_capture(model, ids, config.PARITY_NEW_TOKENS)
        cap["prompt"] = prompt
        text = tok.decode(cap["greedy_ids"], skip_special_tokens=True)
        per_prompt.append(cap)
        print(f"[{i}] {prompt!r}\n    -> {text!r}\n")

    fixture = {
        "meta": {
            "model_name": config.MODEL_NAME,
            "dtype": str(config.DTYPE),
            "device": config.DEVICE,
            "attn_implementation": "eager",
            "use_cache": False,
            "new_tokens": config.PARITY_NEW_TOKENS,
            "topk": TOPK,
            "seed": config.SEED,
            "vocab_size": int(model.config.vocab_size),
            "torch_version": torch.__version__,
            "transformers_version": transformers.__version__,
        },
        "prompts": per_prompt,
    }
    torch.save(fixture, config.REFERENCE_FIXTURE)
    size_mb = config.REFERENCE_FIXTURE.stat().st_size / 1024**2
    print(f"Saved {config.REFERENCE_FIXTURE.relative_to(config.REPO_ROOT)} "
          f"({size_mb:.2f} MB, {len(per_prompt)} prompts)")


if __name__ == "__main__":
    main()
